services:
  - type: web
    name: discord-quote-bot
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    dockerfilePath: ./Dockerfile
